# Base stage for building Angular App
FROM node:18 AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy source code and build
COPY . .
RUN npm run build

# Production stage (Serve Angular app using Node.js with HTTPS)
FROM node:18 AS production
WORKDIR /app

# Copy built Angular files
COPY --from=builder /app/dist/direna-fitpro/browser ./dist

# Install Certbot and dependencies
RUN apt-get update && apt-get install -y certbot python3-certbot-nginx

# Copy SSL certificate and key (will be generated by Certbot)
COPY ./letsencrypt/live/direna.romanixtz.com/fullchain.pem ./cert.pem
COPY ./letsencrypt/live/direna.romanixtz.com/privkey.pem ./key.pem

# Install a simple HTTP server to serve the Angular app
RUN npm install -g http-server

# Expose port 443 for HTTPS
EXPOSE 443

# Serve the Angular app with HTTPS
CMD ["http-server", "dist", "-p", "443", "--ssl", "--cert", "cert.pem", "--key", "key.pem", "--proxy", "https://node_server:4000?"]
