version: '3.8'

services:
  direna_fitpro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: direna_fitpro
    restart: always
    ports:
      - "443:443"  # Map host port 443 to container port 443
    depends_on:
      - node_server
      - certbot

  node_server:
    image: node:18
    container_name: node_server
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt/log:/var/log/letsencrypt
    command: certonly --webroot -w /var/www/html -d direna.romanixtz.com --email amanideveloper1505@gmail.com --agree-tos --non-interactive --keep-until-expiring
