services:
  direna_fitpro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: direna_fitpro
    restart: always
    ports:
      - "443:443"
    depends_on:
      - node_server

  node_server:
    image: node:18
    container_name: node_server
    working_dir: /app
    volumes:
      - .:/app
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
