[build]
  command = "npm ci && npm run build && npm run serve:ssr:direna-fitpro"
  publish = "dist/direna-fitpro/browser"
  functions = "dist/direna-fitpro/server"

[build.environment]
  NODE_VERSION = "18.20.5"
